---
- name: Stop the server
  become_user: postgres
  service:
    name: postgresql
    state: stopped

- name: Backup old data directory
  shell: 'tar -cvzf /tmp/data_backup-`date +%s`.tgz {{ postgresql_data_directory }}'

- name: Remove old data directory
  file:
    path: '{{ postgresql_data_directory }}'
    state: absent
 
- name: Create new data directory
  file:
    path: '{{ postgresql_data_directory }}'
    mode: go-rwx
    owner: '{{ postgresql_admin_user }}'
    state: directory

- name: Pull data from master and start replication on slave
  shell: 'cd {{ postgresql_data_directory }} && pg_basebackup -P -R -X stream -c fast -h {{ primary_host }} -U {{ postgresql_admin_user }} -D ./'

- name: Ensure /var/lib/postgresql belongs to postgres user
  file:
    path: /var/lib/postgresql 
    state: directory
    recurse: true
    owner: postgres

- name: Ensure remote pgpool start script is present
  template:
    src: pgpool_remote_start.j2
    dest: '{{ pgpool2_confdir }}/pgpool_remote_start'
    owner: postgres
    mode: go+rwx

- name: Ensure server is started
  become_user: postgres
  service:
    name: postgresql
    state: started
    enabled: true
