---
- name: Stop the server
  become_user: postgres
  service:
    name: postgresql
    state: stopped

- name: Backup old data directory
  shell: 'tar -cvzf /tmp/data_backup-`date +%s`.tgz {{ postgresql_data_directory }}'

- name: Remove old data directory
  file:
    path: '{{ postgresql_data_directory }}'
    state: absent
 
- name: Create new data directory
  become_user: '{{ postgresql_admin_user }}'
  file:
    path: '{{ postgresql_data_directory }}'
    mode: 0700
    owner: '{{ postgresql_admin_user }}'
    state: directory

- name: Pull data from master and start replication on slave
  become_user: '{{ postgresql_admin_user }}'
  shell: 'cd {{ postgresql_data_directory }} && pg_basebackup -P -R -X stream -c fast -h {{ primary_host }} -U {{ postgresql_admin_user }} -D ./'

- name: Ensure /var/lib/postgresql belongs to postgres user
  file:
    path: /var/lib/postgresql 
    state: directory
    recurse: true
    owner: postgres

- name: Ensure recovery.conf is present
  template:
    src: recovery.conf.j2
    dest: '{{ postgresql_data_directory }}/recovery.conf'
    owner: '{{ postgresql_admin_user }}'

- name: Ensure latest_primary file exists
  file:
    path: '{{ postgresql_data_directory }}/latest_primary'
    state: touch
    owner: '{{ postgresql_admin_user }}'

- name: ... and points to current master
  lineinfile:
    line: '{{ primary_host }}'
    dest: '{{ postgresql_data_directory }}/latest_primary'
    state: present

- name: Ensure server is started
  become_user: postgres
  service:
    name: postgresql
    state: started
    enabled: true
