---
#- name: Setup postgresql
#  hosts: data
#  roles:
#   - ANXS.postgresql

#- name: Set up slaves
#  hosts: data_standby
#  roles:
#    - open_standby_db

- name: Install pgpool2
  become: true
  become_user: root
  hosts: data
  roles:
    - bobishh.pgpool2

  #- name: Install extension
  #hosts:
  #  - data_primary
  #tasks:
  #  - name: Install pgpool_recovery extension
  #    shell: 'psql -U {{ postgresql_admin_user }} -p {{ pgpool2_port }} < "create extension pgpool_recovery"'
