---
- name: Set primary and standby servers
  hosts: all
  become: true
  become_user: root
  vars:
    postgres_databases:
      - name: openbank
  roles:
    - ANXS.postgresql

- name: Provision standby servers
  hosts: data_standby
  become: true
  become_user: root
  roles:
    - open_standby_db
