---
- name: Setup postgresql
  become: true
  become_user: root
  hosts: data
  roles:
    - ANXS.postgresql

- name: Set up slaves
  become: true
  become_user: root
  hosts: data_standby
  roles:
    - open_standby_db

- name: Install pgpool2
  become: true
  become_user: root
  hosts: data
  roles:
    - bobishh.pgpool2
