---
- name: Ensure failover and recovery scripts present
  template:
    src: '{{ item }}'
    dest: '{{ postgresql_data_directory }}/{{ item | regex_replace("\.j2","") }}'
  with_items:
    - failover.sh.j2
    - recovery_1st_stage.j2


- name: Restart postgresql
  service:
    name: postgresql
    state: restarted
