---
pgpool2_pool_passwd: 'postgres'
pgpool2_listen_addresses: '*'
pgpool2_auto_reattach: true

pgpool2_confdir: /etc/pgpool2

pgpool2_pool_user: 'postgres'

pgpool2_sr_check_period: 1
pgpool2_sr_check_user: 'postgres'
pgpool2_sr_check_password: ''


pgpool2_hba_default:
  - comment: unix socket connections
    type: local
    database: all
    user: all
    address: ""
    method: trust

  - comment: local IPv4 connections
    type: host
    database: all
    user: all
    address: 127.0.0.1/32
    method: trust

  - comment: local IPv4 connections
    type: host
    database: all
    user: postgres
    address: 192.168.100.1/24
    method: trust

delay_threshold: 2048

pgpool2_master_slave_mode: on
pgpool2_master_slave_sub_mode: stream

pgpool2_failover_command: '{{ pgpool2_confdir }}/failover.sh %d %M %H %R'

pgpool2_recovery_1st_stage_command: 'recovery_1st_stage'

pgpool2_port: 4242

load_balance_mode: true

pgpool2_backends:
  - name: primary
    host: 192.168.100.10
    port: 5432
    weight: 1
    data_directory: /var/lib/postgresql/9.5/main
    flag: ALLOW_TO_FAILOVER

  - name: standby_1
    host: 192.168.100.20
    port: 5432
    weight: 1000
    data_directory: /var/lib/postgresql/9.5/main
    flag: ALLOW_TO_FAILOVER

  - name: standby_2
    host: 192.168.100.30
    port: 5432
    weight: 1000
    data_directory: /var/lib/postgresql/9.5/main
    flag: ALLOW_TO_FAILOVER
